### PR TITLE
new text added and updated images

### PR DESCRIPTION
**Pull request by joates**
noticed some spelling / typos
merging anyway so we can iterate : )
good work @aboynejames

### CODE REVIEW

**Comment by aboynejames** [comment]
when do you want to do further word smithing on the text?  I ll be free from 11.30 tomorrow,

**Comment by joates** [comment]
already done, you can review my edits [here](https://github.com/Dsensor/website/tree/edits-by-joates) merge them and we rinse-and-repeat until its all done.

btw: where are the .png images ? 
(i reverted back to the defaults so the page is not showing broken links)

**Comment by aboynejames** [comment]
I have forgot to add the pngs  I have them added here https://github.com/Dsensor/website/tree/jamesedits2/public_html/images

**Comment by joates** [comment]
no problem, images are now merged into master (i also removed the default images)

**Comment by Dsensor** [comment]
Thank you

**Pull request merged**
